[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding = {x = 5, y = 0}
startup_mode = "Maximized"

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 17.5
